### ISSUE TITLE
how do you generate the ltm curve with ldr-hdr image pairs 

### ISSUE THREAD

**Issue by xidian-suzhan** [jqtangust/EPCE-HDR#2]
can you share the dataset that you create?If you can't, can you share the method of generating LTM curves?

**Comment by jqtangust** [comment]
Thanks, and I will release the dataset very soon (in a few days).

**Comment by jqtangust** [comment]
Sorry for late, you can download Dataset from: https://drive.google.com/file/d/1VM_WdQTnyW4pzKM88BeCi08Hc0meOkuu/view?usp=drive_link
