### ISSUE TITLE
pretrain model

### ISSUE THREAD

**Issue by gyjung0212** [jqtangust/EPCE-HDR#5]
First of all, thank you for sharing your great project.

I'm trying to train your model, but I'm having trouble constructing the dataset. 
What images should be included in "dataroot_LQ" and "dataroot_GT"?
for example :
    dataroot_LQ => /LDR/image_Gamma/0000/0.200000_img.png
    dataroot_GT => /HDR/image_Gamma/0000/0.200000_img.png 
                               (HDR image is created after running "gamma_tonemapping.py"  and "mulaw.tonemapping.py".)
 is it right?

Additionally, could you provide a pre-trained model?

Thank You!

**Comment by trongan93** [comment]
the same question. The dataset structure was changed. Could you kindly provide the dataset structure and how to match it to the train and test yml? Thanks.

**Comment by jqtangust** [comment]
pls try again for this new version.
